name: provisioning roboshop Infra
on: [workflow_dispatch]
jobs:
  DEV-PLAN:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: terraform init
        run: terraform init -backend-config=env-dev/state.tfvars
      - name: terraform plan
        run: terraform plan -var-file=env-dev/main.tfvars

  DEV-APPLY:
    runs-on: self-hosted
    environment: dev
    needs: DEV-PLAN
    steps:
      - uses: actions/checkout@v4
      - name: terraform init
        run: terraform init -backend-config=env-dev/state.tfvars
      - name: terraform apply
        run: terraform apply -var-file=env-dev/main.tfvars -auto-approve

  QA:
    runs-on: ubuntu-latest
    environment: qa
    needs: DEV-APPLY
    steps:
      - run: echo Dummy job

  UAT:
    runs-on: ubuntu-latest
    environment: uat
    needs: QA
    steps:
      - run: echo Dummy job

  PROD:
    runs-on: self-hosted
    environment: prod
    needs: UAT
    steps:
      - uses: actions/checkout@v4
      - name: terraform init
        run: terraform init -backend-config=env-prd/state.tfvars

